# Generated by Django 4.2 on 2024-01-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productitem_additional_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=255)),
                ('coupon_code', models.CharField(max_length=255)),
                ('coupon_description', models.TextField()),
                ('discount', models.IntegerField(default=0)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
